### ISSUE TITLE
Update to latest Ubuntu release within a fixed timeframe

### ISSUE THREAD

**Issue by jviereck** [machines-in-motion/ubuntu_installation_scripts#10]
At this point we are using Ubuntu LTS. This means we only get updates ever 2 years. In an ideal case we would update to the latest Ubuntu x months after its release.

To make this work, we should
- [ ] Have automatic testing on core packages in place (to check if update will break anything)
- [ ] rt_preempt should be stable / work with newer kernels (there is work to land rt_preempt in Linux main branch on the way, so this hopefully will be a default anyways soon).

\cc @MaximilienNaveau @luator @vincentberenz

**Comment by MaximilienNaveau** [comment]
> At this point we are using Ubuntu LTS. This means we only get updates ever 2 years. In an ideal case we would update to the latest Ubuntu x months after its release.

First I would like to ask you a question, what is the advantage of upgrading every year? We are already struggling to update the version every 2 years so every year seems like a huge overhead.

Moreover I think updating the OS more regularly is impossible to put in place as it would require way to too much work for a very little gain. Indeed every time we upgrade the OS there is a huge undertaking which is composed by:
- 1. Testing the code so that the compilation does not break.
- 2. Installing and carefully testing the rt_preempt patch on the new ubuntu version.
- 3. Verify that all demo can still run in real time on the robots. This part cannot be neglected!
- 4. Update all users computer to the new OS. This part as well takes a major time.

The first 2 checks seems reasonable to perform with every Ubuntu release but not the last 2.
@vincentberenz what do you think?

**Comment by luator** [comment]
I would also vote against using non-LTS versions.  We would actually need to update twice a year since the support duration is only nine months for them.  I don't think that the advantage is big enough to justify the effort.
I also would expect that LTS versions are a bit more stable over time.

I agree, that it would be nice to update to the latest LTS version within a reasonable time frame.  Unfortunately testing can only be automated to a limited degree when working with actual robots (at least as long as we don't have copies of the robots dedicated for CI testing).

**Comment by vincentberenz** [comment]
@MaximilienNaveau @luator 
+1 to what Max and Felix said

**Comment by jviereck** [comment]
Okay, thanks for the feedback. Closing this as WONT-FIX.
